name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: ['20', '22', '23', 'current']

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm test

  test-docs:
    name: Run tests for docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install docs dependencies
        run: npm install
        working-directory: docs

      - name: Test docs build
        run: npm run build
        working-directory: docs
